### ISSUE TITLE
App updates/store blocked on LG TVs

### ISSUE THREAD

**Issue by ShoelaceMan** [hkamran80/blocklists#4]
Hey,

I noticed when using this that I cannot use the LG app store on my TVs. The following domains are the cause of this issue:
us.lgtvsdp.com
us.rdx2.lgtvsdp.com

Whitelisting these ads allows the store to work (but it doesn't show app thumbnails for some reason), and from what I can tell does not show any more ads but I'll admit that I'm not sure how to test that in a foolproof manner. I think it might be worth removing them from the blacklist.

**Comment by hkamran80** [comment]
Sure. I'll go ahead and remove them!
