### ISSUE TITLE
[Remove]: infolink.pavv.co.k is a "non-domain entry"

### ISSUE THREAD

**Issue by kanecko** [hkamran80/blocklists#5]
### Domain

infolink.pavv.co.k

### Why should this domain be added?

"infolink.pavv.co.k" is still in, even though you have fixed it in the now deprecated file #1 
Please go over the text file to make sure not more changes were lost.
Thanks!

  [i] Target: https://raw.githubusercontent.com/hkamran80/blocklists/main/smart-tv
  [✓] Status: Retrieval successful
  [✓] Parsed 202 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "infolink.pavv.co.k"

### List

Smart TV

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hkamran80** [comment]
That's odd. I wonder why it didn't get copied over. I'll fix that.
