### ISSUE TITLE
Checking some DNS blocks

### ISSUE THREAD

**Issue by reichelper** [hkamran80/blocklists#6]
Hi @hkamran80 
thank you for your work and your Smart-TV blocklist.

Could you please check the following DNS entries, because I have to whitelist them.

1. **api.eu.amazonalexa.com** - this is also used by Amazon Echo devices

2. **eu-auth2.samsungosp.com** - this is used by Samsung Smartphones for account login and should not blocked at all

3. **arcus-uswest.amazon.com** - this entry is twice times listed

Thanks

**Comment by hkamran80** [comment]
Sure thing! Thanks for letting me know about these.
